global using Basket.API.Data;
global using Basket.API.Dtos;
global using Basket.API.Exceptions;
global using Basket.API.Models;
global using Carter;
global using FluentValidation;
global using Mapster;
global using Marten;
global using MediatR;
