version: '1.0'

services:
  catalogdb:
    image: postgres:latest
 
  basketdb:
    image: postgres:latest

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server
    
  messagebroker:
    image: rabbitmq:management
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
    